### PR TITLE
Ensure to fetch instance metrics from the right cluster member

### LINKED ISSUE #1102: resource usage view doesn't work properly in a cluster
Hey,

Couldn't wait for 6.3 and wanted to see what the new resource usage graphs looks like : )

Viewing the UI from `lxd1`, the screenshot speaks for itself, resource usage is only shown on the locally running instances:

Image

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- Ensure to fetch instance metrics from the right cluster member
- Add permission handling of the metrics query

Fixes #1102 

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @mas-who or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](../CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - run a clustered backend with instances running on different members
    - ensure the cpu and disk metrics in the instance list and instance detail page show properly
    - test the same on a non-clustered backend

### CODE REVIEW

File: src/context/useMetrics.tsx [hunk 1]
```diff
@@ -0,0 +1,18 @@
+import { useQuery, UseQueryResult } from "@tanstack/react-query";
+import { useAuth } from "./auth";
+import { queryKeys } from "util/queryKeys";
+import { fetchMetrics } from "api/metrics";
+import { LxdMetricGroup } from "types/metrics";
+
+export const useMetrics = (
+  location: string,
+): UseQueryResult<LxdMetricGroup[]> => {
+  const { isRestricted } = useAuth();
```
Comment (mas-who) [inline src/context/useMetrics.tsx:10]: we can use `useServerEntitlements` here to determine if the user has relevant permissions to view metrics i.e. `server admin` || `server can_view_metrics` || `server viewer`.

Shouldn't we also disable the fetch if `isFineGrained` is null?

**Comment by mas-who** [comment]
QA looks good :+1:

File: src/context/useMetrics.tsx (hunk 1 above)
Comment (edlerd) [reply src/context/useMetrics.tsx:10]: This PR is aimed to fix cluster case. To make sure metrics are loaded correctly in a clustered environment, because that was broken before. I didn't aim to resolve the new requirements for permission just yet. Even though this hook is already half of the way done into that direction.

Comment (edlerd) [reply src/context/useMetrics.tsx:10]: Thinking of this, probably best to solve the permission issue in this PR directly. It should be fairly easy, as you suggested. Will update it shortly.

Comment (mas-who) [reply src/context/useMetrics.tsx:10]: Aaah didn't see the second comment, yeah that makes sense, I guess it's easier to deal with it now while the context is there

File: src/api/metrics.tsx [hunk 2]
```diff
@@ -1,9 +1,11 @@
 import parsePrometheusTextFormat from "parse-prometheus-text-format";
 import type { LxdMetricGroup } from "types/metrics";
 
-export const fetchMetrics = (): Promise<LxdMetricGroup[]> => {
+export const fetchMetrics = (target: string): Promise<LxdMetricGroup[]> => {
```
[the remark this answers is not in the document]
Comment (mas-who) [reply src/api/metrics.tsx:4]: oh I see, all good then

**Review by mas-who — APPROVED** [review]
LGTM thanks for the fix :+1:
