### PR TITLE
fix network config for physical and non-managed networks

### LINKED ISSUE #757: Error report -> UPLink Network -> Issue Reading Configuration
After Launch of microcloud setup, i had some problem with the UPLINK network, i can't read any information about this Network via CLI.

Error

Could not find physical in networkTypeToOptionKey

```
eG@https://172.16.14.185:8443/ui/assets/index-b3f3eaed.js:87:30823
ie@https://172.16.14.185:8443/ui/assets/FormMenuItem-f4d64986.js:1:5989
te@https://172.16.14.185:8443/ui/assets/FormMenuItem-f4d64986.js:1:4865
be@https://172.16.14.185:8443/ui/assets/FormMenuItem-f4d64986.js:1:7867
J@https://172.16.14.185:8443/ui/assets/NetworkForm-34d3abf4.js:1:4879
Zg@https://172.16.14.185:8443/ui/assets/index-b3f3eaed.js:38:19529
B1@https://172.16.14.185:8443/ui/assets/index-b3f3eaed.js:40:44027
L1@https://172.16.14.185:8443/ui/assets/index-b3f3eaed.js:40:39765
m$@https://172.16.14.185:8443/ui/assets/index-b3f3eaed.js:40:39693
Cd@https://172.16.14.185:8443/ui/assets/index-b3f3eaed.js:40:39545
Ym@https://172.16.14.185:8443/ui/assets/index-b3f3eaed.js:40:35913
F0@https://172.16.14.185:8443/ui/assets/index-b3f3eaed.js:40:36716
hi@https://172.16.14.185:8443/ui/assets/index-b3f3eaed.js:38:3274
Dn/<@https://172.16.14.185:8443/ui/assets/index-b3f3eaed.js:40:34246

```
from cli 
~$ lxc network info UPLINK
Error: Network interface "UPLINK" not found
~$ lxc network list
+---------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
|     NAME      |   TYPE   | MANAGED |      IPV4       |           IPV6            | DESCRIPTION | USED BY |  STATE  |
+---------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| test          | bridge   | YES     | 10.59.216.1/24  | fd42:88e8:3ae9:adaa::1/64 |             | 0       | CREATED |
+---------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| UPLINK        | physical | YES     |                 |                           |             | 1       | CREATED |
+---------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| bond0         | bond     | NO      |                 |                           |             | 0       |         |
+---------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| bond0.174      | vlan     | NO      |                 |                           |             | 0       |         |
+---------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| br-int        | bridge   | NO      |                 |                           |             | 0       |         |
+---------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| default       | ovn      | YES     | 10.233.146.1/24 | fd42:c097:9e29:5557::1/64 |             | 6       | CREATED |
+---------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+
| lxdovn1       | bridge   | NO      |                 |                           |             | 0       |         |
+---------------+----------+---------+-----------------+---------------------------+-------------+---------+---------+

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- avoid crash when manually trying to access network config physical networks
- show notification for non-managed networks, that explains the configuration is not available
- limit configuration options on physical managed networks
- hide network forwards on physical managed networks
- disable changing of network type on edit network

Fixes #757

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @mas-who or @edlerd for access.
    - With a local copy of this branch, run as described [here](../HACKING.md#setting-up-for-development).
2. Perform the following QA steps:
    - open network configuration page for a managed network
    - change network name in url to a non managed network
    - ensure the page loads and shows a warning (used to crash in this case before)

## Screenshots

before:

image

after:

image

### CODE REVIEW

**Comment by mas-who** [comment]
Interestingly, I tried navigating to the config page for the `docker0` network on my local branch and it didn't crash. `docker0` is not a managed network. :thinking:

File: src/pages/networks/NetworkDetail.tsx [hunk 1]
```diff
@@ -39,6 +37,21 @@ const NetworkDetail: FC = () => {
     return <Loader />;
   }
 
+  const tabs: string[] = ["Overview", "Configuration", "Forwards"].filter(
```
Comment (mas-who) [inline src/pages/networks/NetworkDetail.tsx:40]: Maybe something like this is a bit more clear?

```suggestion
  const getTabs = () => {
    if (!network?.managed) {
      return ["Overview"]
    }
    
    const type = network?.type ?? "";
    if (type === "physical") {
     return ["Overview", "Configuration"];
    }
    
    return ["Overview", "Configuration", "Forwards"];
  }
```

File: src/pages/networks/forms/NetworkFormMain.tsx [hunk 2]
```diff
@@ -61,91 +61,93 @@ const NetworkFormMain: FC<Props> = ({ formik, project }) => {
...
-            name: "ipv4_address",
-            label: "IPv4 address",
-            defaultValue: "auto",
-            children: (
-              <IpAddressSelector
-                id="ipv4_address"
-                address={formik.values.ipv4_address}
-                setAddress={(value) => {
-                  void formik.setFieldValue("ipv4_address", value);
+      {formik.values.networkType !== "physical" && (
```
Comment (mas-who) [inline src/pages/networks/forms/NetworkFormMain.tsx:64]: for my understanding, so a managed network can be of type `physical`? How do we create that kind of network?

Comment (edlerd) [reply src/pages/networks/forms/NetworkFormMain.tsx:64]: Yes, see the linked issue. The user was using microcloud setup that creates a managed physical network.

**Comment by edlerd** [comment]
> Interestingly, I tried navigating to the config page for the `docker0` network on my local branch and it didn't crash. `docker0` is not a managed network. 🤔

Open the configurations tab and it should explode.

**Comment by mas-who** [comment]
> > Interestingly, I tried navigating to the config page for the `docker0` network on my local branch and it didn't crash. `docker0` is not a managed network. 🤔
> 
> Open the configurations tab and it should explode. Edit: Might need to manually add `/configuration` to the url, if you don't have a managed physical network at hand.

Screenshot from 2024-04-30 18-26-11

**Review by mas-who — APPROVED** [review]

**Comment by edlerd** [comment]
> > > Interestingly, I tried navigating to the config page for the `docker0` network on my local branch and it didn't crash. `docker0` is not a managed network. 🤔
> > 
> > 
> > Open the configurations tab and it should explode. Edit: Might need to manually add `/configuration` to the url, if you don't have a managed physical network at hand.
> 
> Screenshot from 2024-04-30 18-26-11

I reproduced it with the released version 0.8. the main branch before this pr should reproduce it as well.

**Review by Laomaque — COMMENTED** [review]
拉去
