### PR TITLE
fix: [WD-31443] total memory in cluster

### LINKED ISSUE #1625: "Total memory" incorrect in a cluster
Hey again!

Image

It says I have 24GiB total memory, but this is a 4 node cluster and they each have 24GiB memory. I think perhaps the wording should be different for a cluster.

LXD 6.5

### PR DESCRIPTION
**Pull request by omarelkashef**
## Done

- Fixes available memory in cluster

Fixes #1625 
## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @Kxiru or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](https://github.com/canonical/lxd-ui/blob/main/CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - Go to Create an instance page and then to Resource Limits tab
    - Create an override for Memory Limit
    - Ensure available memory is reported correctly as:
           (i) a value if you selected a cluster member as target
           (ii) a value if you have not selected a cluster member as target and all the cluster members have equal limits
           (iii) a range if you have not selected a cluster member as target and the cluster members do not have equal limits
     - Go to one instance -> Configuration -> Resource Limits
      - Create an override for Memory Limit
      - Ensure available memory is reported correctly as a value

## Screenshots

image

image

### CODE REVIEW

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 1]
```diff
@@ -33,27 +63,80 @@ const MemoryLimitAvailable: FC<Props> = ({ project }) => {
...
+  }
+  const maxMemory = getAvailableMemory(resources[0]);
+  return (
     <>
-      Total memory: <b>{humanFileSize(maxMemory)}</b>
+      {maxMemory && (
+        <>
+          Total memory:{" "}
+          <b>
+            {humanFileSize(maxMemory)} {!currentMember && "on current member"}
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: I think we should mention the member here as a chip.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 2]
```diff
@@ -33,27 +63,80 @@ const MemoryLimitAvailable: FC<Props> = ({ project }) => {
...
+    return (
+      <>
+        Total memory:{" "}
+        <b>
+          {humanFileSize(minMemory)} - {humanFileSize(maxMemory)}
+        </b>{" "}
+        <Icon
+          name="information"
+          className="help-link-icon"
+          title="The available memory depends on the member that the instance will be created on. You can also specify the member to determine available memory exactly."
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: We should give exact hints how to "also specify the member".

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 3]
```diff
@@ -33,27 +63,80 @@ const MemoryLimitAvailable: FC<Props> = ({ project }) => {
...
   };
 
-  const maxMemory = getAvailableMemory();
+  const getClusterAvailableMemoryRange = (resources: LxdResources[]) => {
+    const sortedResources = resources
+      .map((r) => r.memory.total)
+      .sort((a, b) => a - b);
+
+    if (!project?.config["limits.memory"]) {
+      return [sortedResources[0], sortedResources[sortedResources.length - 1]];
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: Better introduce `const minResource = sortedResources[0]` and `maxResource` to reuse it here and below. Same for the `const projectResource = project.config["limits.memory"]`.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 4]
```diff
@@ -1,30 +1,60 @@
...
-  const {
-    data: resources,
-    error,
-    isLoading,
-  } = useQuery({
-    queryKey: [queryKeys.resources],
-    queryFn: async () => fetchResources(),
-    enabled: canViewResources(),
+  const queries = useQueries({
+    queries: ((!isProfile && values ? clusterMembers : []) ?? [])
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: Why the `!isProfile`?

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 5]
```diff
@@ -1,30 +1,60 @@
...
+import { useClusterMembers } from "context/useClusterMembers";
+import { CLUSTER_GROUP_PREFIX } from "util/instances";
 
 interface Props {
+  formik?: InstanceAndProfileFormikProps;
   project?: LxdProject;
 }
 
-const MemoryLimitAvailable: FC<Props> = ({ project }) => {
+const MemoryLimitAvailable: FC<Props> = ({ formik, project }) => {
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx:25]: The changes here break for the unclustered case, where there are no cluster members. We should activate the queries based on `const isClustered = useIsClustered();`.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 6]
```diff
@@ -1,59 +1,153 @@
...
-    data: resources,
-    error,
-    isLoading,
-  } = useQuery({
-    queryKey: [queryKeys.resources],
-    queryFn: async () => fetchResources(),
-    enabled: canViewResources(),
+  const clusterMemberNames = clusterMembers.map((member) => member.server_name);
+  const queries = useQueries({
+    queries: (isClustered ? clusterMemberNames : [currentServer])
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: The logic here seems off. Just because the environment is clustered shouldn't have an influence on whether the form at hand is targeting an instance for a specific cluster member.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 7]
```diff
@@ -1,59 +1,153 @@
...
+      .filter(
+        (member) => !isClustered || !currentServer || member === currentServer,
+      )
+      .map((member) => ({
+        queryKey: [queryKeys.resources],
+        queryFn: async () => fetchResources(isClustered ? member : ""),
+        enabled: canViewResources(),
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
        enabled: canViewResources() && isClustered,
```
Here we can use the clustered variable to disable the query if not on a cluster.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 8]
```diff
@@ -1,59 +1,153 @@
...
-      return resources?.memory.total;
+  const getAvailableMemory = (resource: LxdResources) => {
+    if (!projectResourceMemory) {
+      return resource?.memory.total;
     }
-    if (!resources?.memory.total) {
-      return limitToBytes(project.config["limits.memory"]);
+    if (!resource?.memory.total) {
+      console.log(limitToBytes(projectResourceMemory));
+
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
```

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 9]
```diff
@@ -1,59 +1,153 @@
...
 }
 
-const MemoryLimitAvailable: FC<Props> = ({ project }) => {
+const MemoryLimitAvailable: FC<Props> = ({ formik, project }) => {
   const notify = useNotify();
   const { canViewResources } = useServerEntitlements();
+  const isClustered = useIsClustered();
+  const { data: clusterMembers = [] } = useClusterMembers();
+  const values = formik?.values;
+  const projectResourceMemory = project?.config["limits.memory"];
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: I think this should directly do the conversion with `Number(limitToBytes` to simplify below code and avoid repetition.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 10]
```diff
@@ -1,59 +1,153 @@
...
   }
-
   if (error) {
     notify.failure("Loading resources failed", error);
   }
-
-  const getAvailableMemory = () => {
-    if (!project?.config["limits.memory"]) {
-      return resources?.memory.total;
+  const getAvailableMemory = (resource: LxdResources) => {
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: I think we should evolve the name a bit to make clear this function is for a targeted cluster member / unclustered case.

File: src/components/forms/DiskSizeSelector.tsx [hunk 11]
```diff
@@ -78,8 +78,7 @@ const DiskSizeSelector: FC<Props> = ({
       </div>
       {(help || helpTotal) && (
         <p className="p-form-help-text">
-          {help}
-          {helpTotal}
+          {help} {helpTotal}
```
Comment (edlerd) [inline src/components/forms/DiskSizeSelector.tsx]: Why did this change? Should it be reverted?

File: src/components/forms/MemoryLimitAvailable.tsx (hunk 7 above)
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: We usually push this logic down into the api layer, see `fetchPoolFromClusterMembers` and its usage in `usePoolFromClusterMembers` for an example.

Then we can have two queries here, one for the clustered and one for the unclustered case that enable / disable based on the context.

All the batching and awaiting the parallel promises for the cluster case is done in the lower layer. This has the advantage, that all the clustered fetching and enabling logic is isolated into a single function and this component stays a bit more close to the rendering and calculation of values for display.

File: src/components/forms/MemoryLimitAvailable.tsx (hunk 6 above)
Comment (omarelkashef) [reply src/components/forms/MemoryLimitAvailable.tsx]: When the environment is unclustered, we use the current server, and when it is, we use the cluster members which are later filtered depending on whether the user has selected a target cluster member

File: src/components/forms/MemoryLimitAvailable.tsx (hunk 7 above)
Comment (omarelkashef) [reply src/components/forms/MemoryLimitAvailable.tsx]: We still need the query for the current server when unclustered.

File: src/components/forms/DiskSizeSelector.tsx (hunk 11 above)
Comment (omarelkashef) [reply src/components/forms/DiskSizeSelector.tsx]: The two texts did not have a space between.

Comment (edlerd) [reply src/components/forms/DiskSizeSelector.tsx]: As both are optional, we render potentially just one with an empty space. Maybe we should only render the space when both are set?

File: src/components/forms/DiskSizeSelector.tsx [hunk 12]
```diff
@@ -77,10 +77,11 @@ const DiskSizeSelector: FC<Props> = ({
...
       {(help || helpTotal) && (
-        <p className="p-form-help-text">
-          {help}
-          {helpTotal}
-        </p>
+        <>
+          {help && <p className="p-form-help-text">{help}</p>}
+          {help && helpTotal && " "}
+          {helpTotal && <p className="p-form-help-text">{helpTotal}</p>}
+        </>
```
Comment (edlerd) [inline src/components/forms/DiskSizeSelector.tsx]:
```suggestion
        <p className="p-form-help-text">
          {help}
          {help && helpTotal && " "}
          {helpTotal}
        </p>
```
A bit simpler.

If we went with the two paragraphs, we wouldn't need the extra space. But I think we want it in a single line, so should keep it within the same paragraph.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 13]
```diff
@@ -1,59 +1,154 @@
...
-const MemoryLimitAvailable: FC<Props> = ({ project }) => {
+const MemoryLimitAvailable: FC<Props> = ({ formik, project }) => {
   const notify = useNotify();
-  const { canViewResources } = useServerEntitlements();
+  const isClustered = useIsClustered();
+  const { data: clusterMembers = [] } = useClusterMembers();
+  const values = formik?.values;
+  const projectResourceMemory = limitToBytes(project?.config["limits.memory"]);
+  const createTarget =
+    (values as CreateInstanceFormValues)?.target ?? undefined;
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: This should probably move into the `currentServer` block below. And we should use `currentServer` instead of `createTarget` in the render far below.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 14]
```diff
@@ -1,59 +1,154 @@
...
+    if (createTarget && !createTarget.startsWith(CLUSTER_GROUP_PREFIX)) {
+      return createTarget;
+    }
+    const location = (values as EditInstanceFormValues)?.location ?? undefined;
+    return location || undefined;
+  })();
+
+  if (currentServer) {
+    clusterMembers.filter((member) => member.server_name === currentServer);
+  }
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: This is a no-op we filter and don't use the result?
```suggestion
```

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 15]
```diff
@@ -1,59 +1,154 @@
...
+
+  const {
+    data: clusteredResources,
+    error: clusteredError,
+    isLoading: isClusteredLoading,
+  } = useClusterMemberResources(clusterMembers);
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: When `currentServer` is set, we should limit this to only load that server's resources, instead of all. I think that is what you tried to do with the filter above. We can inline the filter here maybe?

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 16]
```diff
@@ -1,59 +1,154 @@
...
     }
-    return Math.min(
-      resources.memory.total,
-      Number(limitToBytes(project.config["limits.memory"])),
-    );
+    return Math.min(resource.memory.total, Number(projectResourceMemory));
   };
 
-  const maxMemory = getAvailableMemory();
+  const getClusterAvailableMemoryRange = (resources: LxdResources[]) => {
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: I think we should generalize the two functions into one. Instead of `getSingleResourceAvailableMemory` we can pass `[unClusteredResources]` to the `getClusterAvailableMemoryRange` for the same result.

Also, the render function generalizes between clustered and unclustered similarly. So we can reduce the duplication.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 17]
```diff
@@ -1,59 +1,154 @@
...
+              <>
+                <br />
+                {" on "}
+                <ResourceLink
+                  type="cluster-member"
+                  value={createTarget}
+                  to={`/ui/cluster/member/${encodeURIComponent(createTarget)}`}
+                />
+              </>
+            )}
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: We never have a target in the unclustered case. We only want to show the member when `currentServer` is set.

I would change the layout slightly to say "on cluster member (foo)" where (foo) is the chip. this might fit into a single line with "Total memory: xx".

There is also another case, where the limit comes from the project, we might want to highlight that source as well. To say something like "Total memory: xx (from project configuration)".

So instead of returning an array with `[min, max]` we also need the information if there is a source of the min / max and what it is. It can be empty, cluster member name or the project limit.

Also the qualifier "from project..." or "on cluster member (foo)" should not be bold, only the actual limit.

File: src/api/server.tsx [hunk 18]
```diff
@@ -110,6 +110,33 @@ export const fetchResources = async (
...
+      .then((results) => {
+        const data: LxdResources[] = [];
+        for (let i = 0; i < clusterMembers.length; i++) {
+          const member = clusterMembers[i];
+          const result = results[i];
+          if (result.status === "fulfilled") {
+            const promise = result;
+            data.push(promise.value);
+          } else if (result.status === "rejected") {
+            reject(constructMemberError(result, member.server_name));
```
Comment (edlerd) [inline src/api/server.tsx]: This means we surface an error if any of the cluster members is unhealthy. I am not 100% sure this is the right thing, we might want a more graceful handling. Say you have a 50 member cluster and one node is down, then would you want the error to show or see the limits just for the remaining 49 members? I think the current implementation is fine, as the error should surface. Wdyt?

Comment (omarelkashef) [reply src/api/server.tsx]: If onne cluster member is down, the reporting might be inaccurate if we ignore that error and calculate available memory of the healthy nodes. So, I think we should not report memory limit if any node is down.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 19]
```diff
@@ -1,59 +1,153 @@
...
+              className="help-link-icon"
+              title={`The available memory depends on the member that the instance will be created on. To determine available memory exactly, Select the "Cluster Member" option from the "Target" dropdown and choose a member.`}
+            />
+          </>
+        )}
+      </b>
+      {resourceLink && (
+        <>
+          {" "}
+          on {source} {resourceLink}
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: This should probably be "in project (foo)" and "on cluster member (bar)". But not "on project (foo)" as now..

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 20]
```diff
@@ -1,59 +1,153 @@
...
     }
-    if (!resources?.memory.total) {
-      return limitToBytes(project.config["limits.memory"]);
+    const projectLimit = Number(projectResourceMemory);
+
+    if (sortedResourcesMemories.length === 0) {
+      return {
+        range: [projectLimit, projectLimit],
+        source: "project",
+      };
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx:92]:
```suggestion
      return {
        min: projectLimit
        max:, projectLimit,
        source: "project",
      };
```
Better define a type for this and not use an anonymous array and a named field for source.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 21]
```diff
@@ -1,59 +1,153 @@
...
-    queryKey: [queryKeys.resources],
-    queryFn: async () => fetchResources(),
-    enabled: canViewResources(),
-  });
-
-  if (isLoading) {
+    data: unClusteredResource,
+    error: unClusteredError,
+    isLoading: isUnClusteredLoading,
+  } = useUnClusterMemberResources();
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: This is pretty nice already. I wonder if can combine the data loding to pass in the currentServer into a `useResources` function and it internally loads the cluster members if server is clustered and picks the right query between clustered and unclustered cases. That should simplify the rendering logic in here as we can always refer to the same resources array for both cases. So we remove the conditions between clusteredResources and unClusteredResource

File: src/api/server.tsx [hunk 22]
```diff
@@ -110,6 +110,33 @@ export const fetchResources = async (
...
+      }),
+    )
+      .then((results) => {
+        const data: LxdResources[] = [];
+        for (let i = 0; i < clusterMembers.length; i++) {
+          const member = clusterMembers[i];
+          const result = results[i];
+          if (result.status === "fulfilled") {
+            const promise = result;
+            data.push(promise.value);
```
Comment (edlerd) [inline src/api/server.tsx]:
```suggestion
            data.push(result.value);
```
Why the extra variable?

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 23]
```diff
@@ -1,59 +1,143 @@
...
+    const sortedResourcesMemories = resources
+      .map((r) => r.memory.total)
+      .sort((a, b) => a - b);
+    const minResourceMemory = sortedResourcesMemories[0];
+    const maxResourceMemory =
+      sortedResourcesMemories[sortedResourcesMemories.length - 1];
+    if (!projectResourceMemory) {
+      return {
+        range: [minResourceMemory, maxResourceMemory],
+        source: isClustered && currentServer ? "cluster-member" : "",
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
        source: currentServer ? "cluster-member" : "",
```
I think current server is only set if we are clustered, so we don't need the explicit check here.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 24]
```diff
@@ -1,59 +1,143 @@
...
+  formik?: InstanceAndProfileFormikProps;
   project?: LxdProject;
 }
 
-const MemoryLimitAvailable: FC<Props> = ({ project }) => {
+const MemoryLimitAvailable: FC<Props> = ({ formik, project }) => {
   const notify = useNotify();
-  const { canViewResources } = useServerEntitlements();
+  const isClustered = useIsClustered();
+  const { data: clusterMembers = [] } = useClusterMembers();
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
```
We probably don't need this here. See other comments below.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 25]
```diff
@@ -1,59 +1,143 @@
...
-    error,
-    isLoading,
-  } = useQuery({
-    queryKey: [queryKeys.resources],
-    queryFn: async () => fetchResources(),
-    enabled: canViewResources(),
-  });
+    error: error,
+    isLoading: isLoading,
+  } = useResources(clusterMembers, currentServer);
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
  } = useResources(currentServer);
```
We can push the loading of cluster members into the hook, as we don't need them here.

File: src/components/forms/MemoryLimitAvailable.tsx (hunk 20 above)
Comment (edlerd) [reply src/components/forms/MemoryLimitAvailable.tsx:92]: This seems to still be open.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 26]
```diff
@@ -1,59 +1,143 @@
...
+  let resourceLink = null;
+  if (source === "project") {
+    resourceLink = (
+      <ResourceLink
+        type="project"
+        value={project?.name || "default"}
+        to={`/ui/projects/${encodeURIComponent(project?.name || "default")}`}
+      />
+    );
+  } else if (source === "cluster-member" && currentServer) {
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
  } else if (source === "cluster-member") {
```
I think current server is always defined in this case.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 27]
```diff
@@ -1,59 +1,143 @@
...
+    resourceLink = (
+      <ResourceLink
+        type="cluster-member"
+        value={currentServer}
+        to={`/ui/cluster/member/${encodeURIComponent(currentServer)}`}
+      />
+    );
+  }
+  const showHelpIcon = isClustered && minMemory !== maxMemory;
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
  const showHelpIcon = minMemory !== maxMemory;
```
This is implicitly true. I think we don't have to check for it here.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 28]
```diff
@@ -1,59 +1,143 @@
...
+  let sourceText = "";
+  if (source === "project") {
+    sourceText = "in project";
+  } else if (source === "cluster-member") {
+    sourceText = "on cluster member";
+  }
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: This is repeating the check on source we already have on the definition of the resource link above. I think we should define one function `getSourceQualifier()` that returns the source text and the resource link as a fragment. Then we need to branch on the source only once inside that function. The usage below also gets simpler.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 29]
```diff
@@ -1,59 +1,143 @@
...
+      <b>
+        {humanFileSize(minMemory)}
+        {minMemory !== maxMemory && ` - ${humanFileSize(maxMemory)}`}
+        {showHelpIcon && (
+          <>
+            {" "}
+            <Icon
+              name="information"
+              className="help-link-icon"
+              title={`The available memory depends on the member that the instance will be created on. To determine available memory exactly, Select the "Cluster Member" option from the "Target" dropdown and choose a member.`}
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]: I think we should mention the "Main configuration" as the user has to switch there first to reach the target selector.

File: src/context/useResources.tsx [hunk 30]
```diff
@@ -0,0 +1,31 @@
...
+    enabled: canViewResources() && !isClustered,
+  });
+  const clusteredMembersResourcesQuery = useQuery({
+    queryKey: [queryKeys.resources, clusterMembers],
+    queryFn: async () =>
+      fetchClusterMembersResources(
+        clusterMembers.filter(
+          (member) => !currentServer || member.server_name === currentServer,
+        ),
+      ),
```
Comment (edlerd) [inline src/context/useResources.tsx]: We need to do the filtering of cluster members before and use the filtered list in the query key. Otherwise, there can be cache key collisions with different values for current server

File: src/components/forms/MemoryLimitAvailable.tsx (hunk 20 above)
Comment (omarelkashef) [reply src/components/forms/MemoryLimitAvailable.tsx:92]: A MemoryLimit interface was defined and used in that file.

Comment (edlerd) [reply src/components/forms/MemoryLimitAvailable.tsx:92]: Oh I see, what I meant before though is to change the interface to be a flat object without anonymous array. See suggestion above.

File: src/context/useResources.tsx [hunk 31]
```diff
@@ -0,0 +1,30 @@
...
+import { useServerEntitlements } from "util/entitlements/server";
+import { useIsClustered } from "./useIsClustered";
+import { fetchResources, fetchClusterMembersResources } from "api/server";
+import { useClusterMembers } from "./useClusterMembers";
+
+export const useResources = (currentServerInCluster?: string) => {
+  const isClustered = useIsClustered();
+  const { data: clusterMembers = [] } = useClusterMembers();
+  const { canViewResources } = useServerEntitlements();
+  const unClusteredMembersResourcesQuery = useQuery({
```
Comment (edlerd) [inline src/context/useResources.tsx]:
```suggestion
  const singleNodeQuery = useQuery({
```

File: src/context/useResources.tsx [hunk 32]
```diff
@@ -0,0 +1,30 @@
...
+    queryKey: [queryKeys.resources],
+    queryFn: async () => fetchResources(),
+    enabled: canViewResources() && !isClustered,
+  });
+  const filteredClusterMembers = clusterMembers.filter(
+    (member) =>
+      !currentServerInCluster || member.server_name === currentServerInCluster,
+  );
+  const clusteredMembersResourcesQuery = useQuery({
```
Comment (edlerd) [inline src/context/useResources.tsx]:
```suggestion
  const clusterQuery = useQuery({
```

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 33]
```diff
@@ -1,59 +1,149 @@
...
 }
 
-const MemoryLimitAvailable: FC<Props> = ({ project }) => {
+const MemoryLimitAvailable: FC<Props> = ({ formik, project }) => {
   const notify = useNotify();
-  const { canViewResources } = useServerEntitlements();
+  const isClustered = useIsClustered();
+  const values = formik?.values;
+  const projectResourceMemory = limitToBytes(project?.config["limits.memory"]);
+  const currentServerInCluster = (() => {
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
  const clusterMember = (() => {
```

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 34]
```diff
@@ -1,59 +1,149 @@
...
     data: resources,
-    error,
-    isLoading,
-  } = useQuery({
-    queryKey: [queryKeys.resources],
-    queryFn: async () => fetchResources(),
-    enabled: canViewResources(),
-  });
+    error: error,
+    isLoading: isLoading,
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
    error,
    isLoading,
```

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 35]
```diff
@@ -1,59 +1,149 @@
...
+  } = useResources(currentServerInCluster);
 
   if (isLoading) {
     return <Spinner className="u-loader" text="Loading resources..." />;
   }
-
   if (error) {
     notify.failure("Loading resources failed", error);
+    return null;
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx:45]: Why change the early return here?

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 36]
```diff
@@ -1,59 +1,149 @@
...
   }
 
-  const getAvailableMemory = () => {
-    if (!project?.config["limits.memory"]) {
-      return resources?.memory.total;
+  const getSourceQualifier = () => {
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
  const getSourceQualifier = (source: string) => {
```
I guess without passing it in, this will always return empty.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 37]
```diff
@@ -1,59 +1,149 @@
...
+            to={`/ui/cluster/member/${encodeURIComponent(currentServerInCluster ?? "")}`}
+          />
+        </>
+      );
+    }
+    return null;
+  };
+
+  const getAvailableMemory = (
+    resources: LxdResources[] | LxdResources,
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
```
Here, I think we can rely on the outside scope. Resources comes from the hook above.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 38]
```diff
@@ -1,59 +1,149 @@
...
+  ): MemoryLimit => {
+    resources = Array.isArray(resources) ? resources : [resources];
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
    const resourceArray = Array.isArray(resources) ? resources : [resources];
```
I think this is always a reference, and we should treat `resources` immutable.

File: src/api/server.tsx [hunk 39]
```diff
@@ -110,6 +110,32 @@ export const fetchResources = async (
...
+          } else if (result.status === "rejected") {
+            reject(constructMemberError(result, member.server_name));
+          }
+        }
+        resolve(data);
+      })
+      .catch(reject);
+  });
+};
+
```
Comment (kimanhou) [inline src/api/server.tsx:130]:
```suggestion
export const fetchClusterMembersResources = async (
  clusterMembers: LxdClusterMember[],
): Promise<LxdResources[]> => {
  const results = await Promise.allSettled(
    clusterMembers.map(async (member) => fetchResources(member.server_name)),
  );

  const data: LxdResources[] = [];

  for (let i = 0; i < clusterMembers.length; i++) {
    const member = clusterMembers[i];
    const result = results[i];

    if (result.status === "rejected") {
      throw constructMemberError(result, member.server_name);
    }

    data.push(result.value);
  }

  return data;
};
```

I know that the other functions are written like this, but should we use `async`/`await` ?

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 40]
```diff
@@ -1,59 +1,149 @@
...
-  const maxMemory = getAvailableMemory();
+  const {
+    min: minMemory,
+    max: maxMemory,
+    source,
+  } = getAvailableMemory(resources ?? []);
+  const showHelpIcon = minMemory !== maxMemory;
+  const helpIconText = `The available memory depends on the cluster member that the instance will be created on.\
+  To determine the available memory exactly, go to the "Main configuration" section,\
+  select the "Cluster Member" option from the "Target" dropdown, and choose a member.`;
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
  from the "Target" dropdown, select the "Cluster Member" option and choose a member.`;
```
Better use the order the user has to execute / think in.

File: src/components/forms/DiskSizeSelector.tsx [hunk 41]
```diff
@@ -76,12 +76,11 @@ const DiskSizeSelector: FC<Props> = ({
...
-        <p className="p-form-help-text">
-          {help}
-          {helpTotal}
-        </p>
-      )}
+      <p className="p-form-help-text">
+        {help}
+        {help && helpTotal && " "}
+        {helpTotal}
+      </p>
```
Comment (kimanhou) [inline src/components/forms/DiskSizeSelector.tsx:83]:
```suggestion
      <p className="p-form-help-text">
        {[help, helpTotal].filter(Boolean).join(' ')}
      </p>
```

More elegant but harder to read. Wdyt ?

File: src/components/forms/MemoryLimitSelector.tsx [hunk 42]
```diff
@@ -4,13 +4,19 @@ import type { MemoryLimit } from "types/limits";
 import { BYTES_UNITS, MEM_LIMIT_TYPE } from "types/limits";
 import MemoryLimitAvailable from "components/forms/MemoryLimitAvailable";
 import { useCurrentProject } from "context/useCurrentProject";
+import type { InstanceAndProfileFormikProps } from "./instanceAndProfileFormValues";
 
 interface Props {
+  formik: InstanceAndProfileFormikProps;
```
Comment (edlerd) [inline src/components/forms/MemoryLimitSelector.tsx:10]: There is another use case in `ProjectResourceLimitsForm`, there we should report to total sum of memory available. Should this be a different mode of this component or wdyt?

image

File: src/components/forms/DiskSizeSelector.tsx [hunk 43]
```diff
@@ -76,12 +76,11 @@ const DiskSizeSelector: FC<Props> = ({
...
       </div>
-      {(help || helpTotal) && (
-        <p className="p-form-help-text">
-          {help}
-          {helpTotal}
-        </p>
-      )}
+      <p className="p-form-help-text">
+        {help}
+        {help && helpTotal && " "}
```
Comment (edlerd) [inline src/components/forms/DiskSizeSelector.tsx]:
```suggestion
        {help && helpTotal && <br />}
```
I think a new line would fit better here.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 44]
```diff
@@ -1,59 +1,149 @@
...
+      return undefined;
+    }
+    const createTarget =
+      (values as CreateInstanceFormValues)?.target ?? undefined;
+    if (createTarget && !createTarget.startsWith(CLUSTER_GROUP_PREFIX)) {
+      return createTarget;
+    }
+    const location = (values as EditInstanceFormValues)?.location ?? undefined;
+    return location || undefined;
+  })();
```
Comment (kimanhou) [inline src/components/forms/MemoryLimitAvailable.tsx]: I'm not a fan of immediately invoking a function in a variable.

Either create a function then call it:
```suggestion
    const getCurrentServer = (
    values:
      | CreateInstanceFormValues
      | EditInstanceFormValues
      | CreateProfileFormValues
      | EditProfileFormValues
      | undefined,
    isClustered: boolean,
  ): string | undefined => {
    if (!isClustered || !values) return undefined;

    const target = "target" in values ? values.target : undefined;
    const location = "location" in values ? values.location : undefined;

    if (target && !target.startsWith(CLUSTER_GROUP_PREFIX)) {
      return target;
    }

    return location;
  };

  const currentServerInCluster = getCurrentServer(values, isClustered);
```

Or keep things inline:
```suggestion
  const { target } = values as CreateInstanceFormValues;
  const { location } = values as EditInstanceFormValues;
  const isTargetGroup = target?.startsWith(CLUSTER_GROUP_PREFIX);
  const validTarget = target && !isTargetGroup ? target : undefined;
  const currentServerInCluster = isClustered
    ? (validTarget ?? location)
    : undefined;
```

Those suggestions need refining, especially with types but you get the idea.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 45]
```diff
@@ -1,59 +1,149 @@
...
+        <>
+          {"in project "}
+          <ResourceLink
+            type="project"
+            value={project?.name || "default"}
+            to={`/ui/projects/${encodeURIComponent(project?.name || "default")}`}
+          />
+        </>
+      );
+    } else if (source === "cluster-member") {
```
Comment (kimanhou) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
    } if (source === "cluster-member") {
```

You don't need `else` after a `return`

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 46]
```diff
@@ -1,59 +1,149 @@
...
     }
-    return Math.min(
-      resources.memory.total,
-      Number(limitToBytes(project.config["limits.memory"])),
-    );
+    return {
+      min: Math.min(minResourceMemory, projectLimit),
+      max: Math.min(maxResourceMemory, projectLimit),
+      source: "",
+    };
```
Comment (kimanhou) [inline src/components/forms/MemoryLimitAvailable.tsx]: Can `resources` be empty ? If so, I think it crashes.
Something like this should fix it:
```
  const getAvailableMemory = (
    resources: LxdResources[] | LxdResources,
  ): MemoryLimit => {
    const list = Array.isArray(resources) ? resources : [resources];
    const projectLimit = projectResourceMemory
      ? Number(projectResourceMemory)
      : null;

    if (list.length === 0) {
      return {
        min: projectLimit ?? 0,
        max: projectLimit ?? 0,
        source: "project",
      };
    }

    const memories = list.map((r) => r.memory.total);
    const hwMin = Math.min(...memories);
    const hwMax = Math.max(...memories);

    if (projectLimit === null) {
      return {
        min: hwMin,
        max: hwMax,
        source: currentServerInCluster ? "cluster-member" : "",
      };
    }

    return {
      min: Math.min(hwMin, projectLimit),
      max: Math.min(hwMax, projectLimit),
      source: "",
    };
  };
```

File: src/components/forms/MemoryLimitSelector.tsx (hunk 42 above)
Comment (edlerd) [reply src/components/forms/MemoryLimitSelector.tsx:10]: You built the nice abstraction to load resources for both cluster and single node backends.

I think we should introduce a new `ProjectMemoryLimit` component with the different semantic of summing the memory limits per member. Should be very easy to build now with the reusable `useResources` function. In the project case we have no current server, we have no project limit so it is a simple sum over the returned array or the limit from the single node.

File: src/api/server.tsx (hunk 39 above)
Comment (omarelkashef) [reply src/api/server.tsx:130]: I initially wanted to match the convention, but your suggestion is cleaner. I think we should do it.

File: src/components/forms/DiskSizeSelector.tsx (hunk 41 above)
Comment (omarelkashef) [reply src/components/forms/DiskSizeSelector.tsx:83]: @edlerd suggested to use a `<br />` between the two texts.

File: src/components/forms/MemoryLimitAvailable.tsx (hunk 44 above)
Comment (omarelkashef) [reply src/components/forms/MemoryLimitAvailable.tsx]: I prefer the second option.

File: src/components/forms/DiskSizeSelector.tsx (hunk 41 above)
Comment (kimanhou) [reply src/components/forms/DiskSizeSelector.tsx:83]: Yeah, I saw afterwards. That breaks my elegant solution ! 🫩

File: src/api/server.tsx (hunk 39 above)
Comment (kimanhou) [reply src/api/server.tsx:130]: You would then have to change the other functions in this file at least, which could be a big change. Are you okay with that ? If not, do it in a separate PR. Or create a JIRA ticket to do it later (and not necessarily by you)

File: src/components/forms/MemoryLimitSelector.tsx (hunk 42 above)
Comment (omarelkashef) [reply src/components/forms/MemoryLimitSelector.tsx:10]: Yes, that is an easy component.

File: src/components/forms/MemoryLimitAvailable.tsx (hunk 35 above)
Comment (edlerd) [reply src/components/forms/MemoryLimitAvailable.tsx:45]: This is still open.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 47]
```diff
@@ -1,59 +1,134 @@
...
-    if (!resources?.memory.total) {
-      return limitToBytes(project.config["limits.memory"]);
+    return null;
+  };
+
+  const getAvailableMemory = (): MemoryLimit => {
+    const resourceArray = Array.isArray(resources) ? resources : [resources];
+    const projectLimit = Number(projectResourceMemory);
+
+    if (resourceArray.length === 0) {
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
    if (resourceArray.length === 0 || projectLimit < minResourceMemory ) {
```
If the project limit is the lower bound, we should report it as such.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 48]
```diff
@@ -1,59 +1,134 @@
...
+      };
     }
-    return Math.min(
-      resources.memory.total,
-      Number(limitToBytes(project.config["limits.memory"])),
-    );
+    const resourcesMemories = resourceArray.map((r) => r.memory.total);
+    const minResourceMemory = Math.min(...resourcesMemories);
+    const maxResourceMemory = Math.max(...resourcesMemories);
+    if (!projectResourceMemory) {
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
    if (!projectResourceMemory || maxResourceMemory < projectResourceMemory) {
```
If the member resources are the limiting factor, report them as such.

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 49]
```diff
@@ -1,59 +1,134 @@
...
+            {" "}
+            <Icon
+              name="information"
+              className="help-link-icon"
+              title={helpIconText}
+            />
+          </>
+        )}
+      </b>{" "}
+      {getSourceQualifier(source)}
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx:134]: The spacing is subobtimal here:

image


I think we should put the qualifier in its own line:

image

File: src/components/forms/MemoryLimitAvailable.tsx [hunk 50]
```diff
@@ -1,59 +1,134 @@
...
+        min: minResourceMemory,
+        max: maxResourceMemory,
+        source: clusterMember ? "cluster-member" : "",
+      };
+    }
+
+    return {
+      min: Math.min(minResourceMemory, projectLimit),
+      max: Math.min(maxResourceMemory, projectLimit),
+      source: "",
```
Comment (edlerd) [inline src/components/forms/MemoryLimitAvailable.tsx]:
```suggestion
      min: minResourceMemory,
      max: projectLimit,
      source: "",
```
I think all other cases are handled above now. 

The remaining case is a wired edge. The project limit is between two cluster member resources. I think it is OK to not report where the limit comes from in that case, though.

File: src/components/forms/MemoryLimitAvailable.tsx (hunk 35 above)
Comment (omarelkashef) [reply src/components/forms/MemoryLimitAvailable.tsx:45]: Which early return is changed?  This if statement is still there
``` 
 if (error) {
    notify.failure("Loading resources failed", error);
    return null;
  }```

Comment (edlerd) [reply src/components/forms/MemoryLimitAvailable.tsx:45]: I was curious why adding the early return in that condition.

Comment (omarelkashef) [reply src/components/forms/MemoryLimitAvailable.tsx:45]: If we have an error in loading the resources, the component is not useful anymore. We should not be displaying anything in that case.

Comment (edlerd) [reply src/components/forms/MemoryLimitAvailable.tsx:45]: I see, seems correct. Thanks :)

File: src/components/forms/MemoryLimitAvailable.tsx (hunk 50 above)
Comment (omarelkashef) [reply src/components/forms/MemoryLimitAvailable.tsx]: Yes, there are a couple of edge cases that would make the code more complicated and it is not worth it to report the limit in that case.

Comment (edlerd) [reply src/components/forms/MemoryLimitAvailable.tsx]: Sounds good to me.
I think we should simplify by removing the Math.min / Math.max cases though, to make clear which edge case remains here.
