### PR TITLE
fix: [WD-32286] total cpu limit in cluster

### LINKED ISSUE #1625: "Total memory" incorrect in a cluster
Hey again!

Image

It says I have 24GiB total memory, but this is a 4 node cluster and they each have 24GiB memory. I think perhaps the wording should be different for a cluster.

LXD 6.5

### PR DESCRIPTION
**Pull request by omarelkashef**
## Done

- Fixes total cpu limit in cluster

Fixes #1625 

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @Kxiru or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](https://github.com/canonical/lxd-ui/blob/main/CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - Go to Create an instance page and then to Resource Limits tab
    - Create an override for CPU Limit
    - Ensure CPU limit is reported correctly as:
        (i) a value if you are in a non-cluster environment
        (ii) a value if you selected a cluster member as target
        (iii) a value if you have not selected a cluster member as target and all the cluster members have equal limits
        (iv) a range if you have not selected a cluster member as target and the cluster members do not have equal limits
    - Go to one instance -> Configuration -> Resource Limits
    - Create an override for Exposed CPU Limit
    - Ensure available memory is reported correctly as a value
    - Go to a project configuration page -> Resource Limit
    - Create an override for Exposed CPU Limit
    - Ensure CPU limit is reported correctly as the limit of the server in non-cluster environment and the sum of all nodes' limits in clustered environment

## Screenshots

image

image

### CODE REVIEW

File: src/util/resourceLimits.tsx [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+export type ResourceLimitSource = "project" | "cluster-member";
+export interface ResourceLimit {
+  min: number;
+  max: number;
+  source?: ResourceLimitSource;
+}
+
+export const getResourceLimit = (
+  resources: number[],
+  isClusterMemberDefined: boolean,
```
Comment (edlerd) [inline src/util/resourceLimits.tsx]:
```suggestion
  clusterMember: string | undefined,
```
I think passing in the member and checking on it below is bit simpler.

File: src/components/forms/CpuLimitAvailable.tsx [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+  const resourceArray = Array.isArray(resources) ? resources : [resources];
+  const {
+    min: minCpu,
+    max: maxCpu,
+    source,
+  } = getResourceLimit(
+    resourceArray.map((r) => r.cpu.total),
+    !!clusterMember,
+    projectResourceCpu,
+  );
```
Comment (edlerd) [inline src/components/forms/CpuLimitAvailable.tsx]: This is duplicating from `MemoryLimitAvailable`. Maybe instead of extracting the `getResourceLimit` we can define a hook like below. It can fetch via `useResources` internally, do all the calculations from `getResourceLimit` and the ones above. Instead of handling loading and error state, we return null if the max returned is not defined. Wdyt?
```
const {
    min: minCpu,
    max: maxCpu,
    source,
  } = useResourceLimit(projectResourceCpu)
```

**Review by edlerd — COMMENTED** [review]
Works nicely, two ideas to improve a bit on the code structure.

File: src/components/forms/CpuLimitAvailable.tsx (hunk 2 above)
Comment (omarelkashef) [reply src/components/forms/CpuLimitAvailable.tsx]: We will still need to handle the loading state in the component to display a spinner and handle the null returned in the case of error, so we will end up with roughly the same amount of duplication. Is it worth it?

Comment (edlerd) [reply src/components/forms/CpuLimitAvailable.tsx]: I was thinking to remove both. Render null if loading or on error case. The available resources will not appear in those cases. Wdyt?

Comment (omarelkashef) [reply src/components/forms/CpuLimitAvailable.tsx]: Ok, I updated the components to use useResourceLimit hook,

Comment (omarelkashef) [reply src/components/forms/CpuLimitAvailable.tsx]: I will refactor some more code.

File: src/util/resourceLimits.tsx [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+
+  return {
+    min: minResource,
+    max: projectLimit,
+    sourceType: undefined,
+    sourceName: undefined,
+  };
+};
+
+export const getResourceLimitIcon = (
```
Comment (edlerd) [inline src/util/resourceLimits.tsx]: Please transform this into a regular react component in a dedicated file.

To be called as `<ResourceLimitIcon source={... />` instead of a plain JS function.

File: src/pages/projects/ProjectCpuLimitInput.tsx [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+
+type Props = InputProps;
+
+export const ProjectCpuLimitInput: FC<Props> = ({ help, ...props }) => {
+  const notify = useNotify();
+
+  const { data: resources = [], error, isLoading } = useResources();
+  let sumCpuLimit = null;
+  if (isLoading) {
+    sumCpuLimit = <Spinner className="u-loader" text="Loading resources..." />;
```
Comment (edlerd) [inline src/pages/projects/ProjectCpuLimitInput.tsx]: This is unexpected. The variable with name `sumCpuLimit` should not hold a spinner. We could just set it to null here as well in my opinion.

File: src/pages/projects/ProjectCpuLimitInput.tsx [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+    <>
+      Total number of CPU cores: <b>{sumCpuLimit}</b>
+    </>
+  ) : (
+    ""
+  );
+
+  const helpText = (
+    <>
+      {help} {help && sumCpuLimitText && <br />}
```
Comment (edlerd) [inline src/pages/projects/ProjectCpuLimitInput.tsx]:
```suggestion
      {help}
      {help && sumCpuLimitText && <br />}
```
Slightly clearer formatting.

File: src/pages/projects/ProjectCpuLimitInput.tsx [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+  let sumCpuLimit = null;
+  if (isLoading) {
+    sumCpuLimit = <Spinner className="u-loader" text="Loading resources..." />;
+  }
+  if (error) {
+    notify.failure("Loading resources failed", error);
+    sumCpuLimit = null;
+  }
+  if (resources) {
+    const resourceArray = Array.isArray(resources) ? resources : [resources];
```
Comment (edlerd) [inline src/pages/projects/ProjectCpuLimitInput.tsx]: How about a new `ensureArray = (foo) => Array.isArray(foo) ? foo : [foo]` helper to be reused here and in other places?

File: src/context/useResourceLimit.tsx [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+import type { CreateInstanceFormValues } from "pages/instances/CreateInstance";
+import type { EditInstanceFormValues } from "pages/instances/EditInstance";
+import type { LxdResources } from "types/resources";
+import { CLUSTER_GROUP_PREFIX } from "util/instances";
+import { getResourceLimit } from "util/resourceLimits";
+import { useIsClustered } from "./useIsClustered";
+import type { LxdProject } from "types/project";
+
+export const useResourceLimit = (
+  resourceExtractor: (resources: LxdResources) => number,
```
Comment (edlerd) [inline src/context/useResourceLimit.tsx]:
```suggestion
  mode: "cpu" | "memory",
```
This extractor pattern makes it fairly hard to reason about what the code is doing as we jump in and out of the local function. Maybe better introduce a more simple mode field, that we handle locally in this function.

File: src/context/useResourceLimit.tsx [hunk 8]
```diff
@@ -0,0 +1,41 @@
...
+  formValues: CreateInstanceFormValues | EditInstanceFormValues,
+  project?: LxdProject,
+  projectResourceLimit?: number,
```
Comment (edlerd) [inline src/context/useResourceLimit.tsx]:
```suggestion
```
I think with the `mode` in place, we can move this into this function as well.

File: src/context/useResourceLimit.tsx [hunk 9]
```diff
@@ -0,0 +1,41 @@
...
+import type { LxdResources } from "types/resources";
+import { CLUSTER_GROUP_PREFIX } from "util/instances";
+import { getResourceLimit } from "util/resourceLimits";
+import { useIsClustered } from "./useIsClustered";
+import type { LxdProject } from "types/project";
+
+export const useResourceLimit = (
+  resourceExtractor: (resources: LxdResources) => number,
+  formValues: CreateInstanceFormValues | EditInstanceFormValues,
+  project?: LxdProject,
```
Comment (edlerd) [inline src/context/useResourceLimit.tsx]:
```suggestion
```
If you follow this project variable upwards, we can pull this into the function as `  const { project } = useCurrentProject();`. And then remove the prop drilling through many of the layers as no other usages of `project` remain upstream.

**Review by edlerd — COMMENTED** [review]
Good generalization with the new `useResourceLimit` function! Some ideas simplify the structure below. The goal is to increase maintainability and increase readability.

File: src/context/useResourceLimit.tsx [hunk 10]
```diff
@@ -0,0 +1,56 @@
...
+  const clusterMember = isClustered ? (validTarget ?? location) : undefined;
+  const { data: resources, error, isLoading } = useResources(clusterMember);
+  const { project } = useCurrentProject();
+  const resourceLimitName = mode === "memory" ? "limits.memory" : "limits.cpu";
+  const projectResourceLimit = project?.config[resourceLimitName]
+    ? limitToBytes(project?.config[resourceLimitName])
+    : undefined;
+
+  if (error) {
+    notify.failure("Loading resources failed", error);
```
Comment (edlerd) [inline src/context/useResourceLimit.tsx:34]:
```suggestion
    notify.failure("Loading resources failed", error);
    return null;
```
Shall we return here, not to present a wrongly calculate limit based on project configuration?

File: src/pages/projects/ProjectCpuLimitInput.tsx [hunk 11]
```diff
@@ -0,0 +1,42 @@
...
+      0,
+    );
+  }
+  const sumCpuLimitText = sumCpuLimit ? (
+    <>
+      Total number of CPU cores: <b>{sumCpuLimit}</b>
+    </>
+  ) : (
+    ""
+  );
```
Comment (edlerd) [inline src/pages/projects/ProjectCpuLimitInput.tsx]:
```suggestion
  const limitSum = ensureArray(resources).reduce(
    (sum, resource) => sum + resource.cpu.total,
    0,
  );
  const hasLimits = limitSum > 0;
  const limitText = hasLimits ? (
    <>
      Total number of CPU cores: <b>{limitSum}</b>
    </>
  ) : null;
```
A bit simpler?

**Review by edlerd — APPROVED** [review]
QA LGTM, just two nitpicks on code.

File: src/pages/projects/ProjectCpuLimitInput.tsx (hunk 11 above)
Comment (omarelkashef) [reply src/pages/projects/ProjectCpuLimitInput.tsx]: It is indeed simpler.
