### PR TITLE
fix(onboarding) simplify chrome on linux browser certificate import steps

### LINKED ISSUE #1426: Doc: Chrome (linux) url to pfx import
Hello, would it be possible to change url pointing to pfx import for Chrome to `chrome://certificate-manager/clientcerts/platformclientcerts`?

On new versions of chrome (139.0.7258.127), menu for importing is divided into 3 sub categories and you have to navigate to `Your Certificates`, otherwise it will not allow you to import it.

Image
 
Thank You

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- simplify chrome on linux browser certificate import steps

Fixes #1426

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @Kxiru or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](https://github.com/canonical/lxd-ui/blob/main/CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - open onboarding steps from chrome

## Screenshots

image

### CODE REVIEW

File: src/pages/login/BrowserImport.tsx [hunk 1]
```diff
@@ -105,17 +105,13 @@ const BrowserImport: FC = () => {
             <ul className="p-list--divided u-no-margin--bottom">
               {downloadPfx}
               <li className="p-list__item">
-                Go to Chrome&apos;s certificate manager:
+                Go to Chrome&apos;s certificate manager import page:
```
Comment (Kxiru) [inline src/pages/login/BrowserImport.tsx]: The wording here is a bit awkward. How about:
- Reverting back to "certificate manager"?
- "imported certificates page"
- " 'import certificate' page"
- "Go to the import certificate page within Chrome's certificate manager"?

For reference:
image
And it's parent page:
image

We can always leave it as is?

**Review by Kxiru — DISMISSED** [review]

File: src/pages/login/BrowserImport.tsx (hunk 1 above)
Comment (edlerd) [reply src/pages/login/BrowserImport.tsx]: I like the "Go to the import certificate page within Chrome's certificate manager" one, as it is making there is an extra step from the certificate manager. Adopted the suggestion just now.

**Review by Kxiru — APPROVED** [review]
This looks good to me! Thank you for being receptive to my feedback :)
