### PR TITLE
Fix storage naming

### LINKED ISSUE #332: Breadcrumb is Missing for Storages Page
On other pages such as instances and profiles as you drill down into pages a breadcrumb is shown top-left (e.g. Profiles > default) that allows you click the previous page name to traverse back up the chain.

This is missing from the Storages page. 

If you click on default in storages - it should show "Storages > default" top left with the "Storages" part being a link to take you back to the default Storages page.

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- rename storage/-s to storage-pools
- rename menu entry to "storage"
- rename heading to "storage pools" on the list page
- add breadcrumb to storage pool detail page

Fixes #332

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @lorumic or @edlerd for access.
    - With a local copy of this branch, run as described in the [Readme](https://github.com/canonical/lxd-ui#setting-up-for-development).
2. Perform the following QA steps:
    - check storage pages

### CODE REVIEW

File: src/pages/storage/StorageDetailHeader.tsx [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+      controls={
+        <DeleteStorageBtn
+          key="delete"
+          storage={storagePool}
+          project={project}
+        />
+      }
+      isLoaded={true}
+      formik={formik}
+      renameDisabledReason="Cannot rename storage pools"
```
Comment (lorumic) [inline src/pages/storage/StorageDetailHeader.tsx:69]: This disables the rename of storage pools completely - is there a reason why we want to do that? And if we do want to disable it, why do we need the API function, the formik etc.? It's confusing because the infrastructure makes you think that you can rename, but in fact you can't.

**Comment by al-bakalova** [comment]
@edlerd This looks good to me.
We actually wanted to try to fit "Storage pools" in the side navigation. I tried replacing it in the browser and it looks good. Could you please update that one as well?

**Comment by lorumic** [comment]
> @edlerd This looks good to me. We actually wanted to try to fit "Storage pools" in the side navigation. I tried replacing it in the browser and it looks good. Could you please update that one as well?

True, it takes approximately the same width as the "Configuration" label just below it:

image

File: src/pages/storage/StorageForm.tsx
[the remark this answers is not in the document]
Comment (edlerd) [reply src/pages/storage/StorageForm.tsx:1]: Yes, I forgot that initially, just added it.

File: src/pages/storage/StorageDetailHeader.tsx (hunk 1 above)
Comment (edlerd) [reply src/pages/storage/StorageDetailHeader.tsx:69]: The API gave me a "feature not implemented" error on renaming of storage pools. I assume it is a thing that is planned for later. Hence I added support for it with this message.

**Comment by edlerd** [comment]
> > @edlerd This looks good to me. We actually wanted to try to fit "Storage pools" in the side navigation. I tried replacing it in the browser and it looks good. Could you please update that one as well?
> 
> True, it takes approximately the same width as the "Configuration" label just below it:

Somehow I missed that it actually fits. Fixed it just now.

File: src/components/Navigation.tsx [hunk 2]
```diff
@@ -126,14 +126,14 @@ const Navigation: FC = () => {
                       <li className="p-side-navigation__item--title secondary">
                         <NavLink
                           className="p-side-navigation__link"
-                          to={`/ui/${project}/storages`}
-                          title={`Storages (${project})`}
+                          to={`/ui/${project}/storage`}
+                          title={`Storage (${project})`}
```
Comment (lorumic) [inline src/components/Navigation.tsx:130]: Should the title stay as "Storage" only?

**Comment by al-bakalova** [comment]
@edlerd Looks good to me. Thanks for applying all the changes!

**Review by lorumic — APPROVED** [review]
