### PR TITLE
fix(instance) clear error on instance console when the instance is reaching a stopped status

### LINKED ISSUE #1842: Unexpected close on console with clean shutdown
Reported in https://github.com/canonical/lxd-ui/issues/1745 but don't want it to get lost in the page load issue.

When I reboot or poweroff a VM, the Console page will show an error "unexpected close".

This close is not unexpected when a VM is doing a clean shutdown. 

Does the LXD daemon expose a clean shutdown signal for the websocket for the graphical console?

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- fix(instance) clear error on instance console when the instance is reaching a stopped status

Fixes #1842

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @Kxiru or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](https://github.com/canonical/lxd-ui/blob/main/CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - open graphic console on a running instance and stop the instance, ensure no error is displayed
    - open text console on a stopped instance, ensure the info is visible
    - open text console on a running instance and stop the instance, ensure the info is visible

## Screenshots

image

image

### CODE REVIEW

File: src/pages/instances/InstanceConsole.tsx [hunk 1]
```diff
@@ -34,6 +34,22 @@ const InstanceConsole: FC<Props> = ({ instance }) => {
 
   const isRunning = isInstanceRunning(instance);
 
+  const clearErrorOnStop = () => {
+    const isStopped = instance.status !== "Stopped";
```
Comment (omarelkashef) [inline src/pages/instances/InstanceConsole.tsx]: These variables are the opposite of what they are supposed to be.  They should be `const isStopped = instance.status === "Stopped";` and `const hasErrorOpen = notify.notification?.type === "negative";`

File: src/pages/instances/InstanceConsole.tsx [hunk 2]
```diff
@@ -1,5 +1,5 @@
 import type { FC } from "react";
```
Comment (omarelkashef) [inline src/pages/instances/InstanceConsole.tsx:1]: I still see an error when I stop the instance.

Image

File: src/pages/instances/InstanceConsole.tsx (hunk 1 above)
Comment (edlerd) [reply src/pages/instances/InstanceConsole.tsx]: Mixed up this bit on refining the PR. should be fixed now.

File: src/pages/instances/InstanceConsole.tsx (hunk 2 above)
Comment (edlerd) [reply src/pages/instances/InstanceConsole.tsx:1]: thanks for catching those mixups. should work now as intended.

**Comment by edlerd** [comment]
@omarelkashef thanks for the review. I changed the logic a bit not to report any error on stopping.
