### PR TITLE
fix(instance) avoid graphic console to surface connection close error when leaving the tab

### LINKED ISSUE #1658: console socket close errors everytime you leave the page
Today with the new LXD 6.6 and ui 0.19

a 4 node cluster with haproxy in front

Switching back and forth between Console and Terminal or Overview page, every time I am greeted with the following errors from the console page

Image

Image

Image

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- fix(instance) avoid graphic console to surface connection close error when leaving the tab

Fixes #1658

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @Kxiru or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](https://github.com/canonical/lxd-ui/blob/main/CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - open a VM graphic console
    - switch to any other tab (or to the text console)
    - ensure no error surfaces.

### CODE REVIEW

File: src/pages/instances/InstanceTextConsole.tsx [hunk 1]
```diff
@@ -38,6 +38,15 @@ const InstanceTextConsole: FC<Props> = ({
...
   const notify = useNotify();
+  const isMounted = useRef(true);
+
+  useEffect(() => {
+    return () => {
+      isMounted.current = false;
+    };
+  }, []);
+
+  console.log(isMounted);
```
Comment (kimanhou) [inline src/pages/instances/InstanceTextConsole.tsx]:
```suggestion
```

Please remove `console.log`

File: src/pages/instances/InstanceTextConsole.tsx [hunk 2]
```diff
@@ -54,7 +63,9 @@ const InstanceTextConsole: FC<Props> = ({
   const isRunning = isInstanceRunning(instance);
 
   const handleError = (e: object) => {
-    onFailure("Error", e);
+    if (isMounted.current) {
+      onFailure("Error", e);
+    }
```
Comment (kimanhou) [inline src/pages/instances/InstanceTextConsole.tsx:61]:
```suggestion
    const handleError = (e: object, message?: string) => {
      if (isMounted.current) {
        onFailure("Console error", e, message);
      }
  };
```

Same as in `InstanceGraphicConsole` ?

File: src/pages/instances/InstanceTextConsole.tsx (hunk 1 above)
Comment (edlerd) [reply src/pages/instances/InstanceTextConsole.tsx]: good catch, forgot it from dev.

File: src/pages/instances/InstanceTextConsole.tsx (hunk 2 above)
Comment (edlerd) [reply src/pages/instances/InstanceTextConsole.tsx:61]: good point. I moved this into a hook, so we can reuse it.

**Review by kimanhou — APPROVED** [review]
Thank you for the new hook !
