### PR TITLE
fix: remove spaces from custom iso name

### LINKED ISSUE #1057: Error when trying to upload custom ISO
Image

Image

Ubuntu Server 24.10 all updates installed with LXD installed during setup ( Version 5.21.2-ui-0.8.4 )

### PR DESCRIPTION
**Pull request by mas-who**
## Done

- Remove spaces from uploaded custom iso file name
- Prevent custom iso alias with spaces

Fixes #1057 

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @mas-who or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](../CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - Upload a custom iso with spaces in its file name, make sure the auto populated alias does not contain spaces.
    - Try change the alias so that it contains spaces

### CODE REVIEW

File: src/pages/storage/UploadCustomIso.tsx [hunk 1]
```diff
@@ -98,10 +98,12 @@ const UploadCustomIso: FC<Props> = ({ onCancel, onFinish }) => {
     if (e.target.files) {
       const file = e.target.files[0];
       setFile(file);
-      setName(file.name);
+      setName(file.name.replaceAll(" ", "-"));
```
Comment (edlerd) [inline src/pages/storage/UploadCustomIso.tsx:101]: I think we should be more strict and only allow alphanumeric chars and -. Everything else should be replaced with "-". Similar to what `sanitizeInstanceName` is doing.

**Review by edlerd — APPROVED** [review]
Thanks for fixing this so quickly. One idea below, we might want to be more strict with the allowed characters, as filenames could come with random Unicode chars and I suspect they might cause issues as well.

File: src/pages/storage/UploadCustomIso.tsx (hunk 1 above)
Comment (mas-who) [reply src/pages/storage/UploadCustomIso.tsx:101]: I thought about using `sanitizeInstanceName` but it is too strict for custom iso alias name. I am not sure if there are any other restrictions either than spaces. Should we just apply the same rules as `sanitizeInstanceName`?

Comment (edlerd) [reply src/pages/storage/UploadCustomIso.tsx:101]: so I think we can't reuse it, but a very similar check should do.

Comment (mas-who) [reply src/pages/storage/UploadCustomIso.tsx]: done, please have a look

**Review by edlerd — APPROVED** [review]
LGTM, thanks for fixing this bug :+1:

**Comment by edlerd** [comment]
Something odd came up in QA: When changing the alias to contain a space, the modal with jumps around.

**Comment by mas-who** [comment]
> Something odd came up in QA: When changing the alias to contain a space, the modal width jumps around.
> 
>  Screencast.from.2025-01-15.17-55-12.mp4

Right, the modal is constrained by a 80rem max-width which leads to the horizontal shift when the error message appears. I've applied a max width to the error message itself which resolves the issue. The current behaviour is that the error message will wrap. We could also do truncation but I think wrapping is better as the error message becomes clearly visible wdyt?

File: src/pages/storage/UploadCustomIso.tsx [hunk 2]
```diff
@@ -122,6 +128,14 @@ const UploadCustomIso: FC<Props> = ({ onCancel, onFinish }) => {
           value={name}
           onChange={(e) => setName(e.target.value)}
           disabled={file === null}
+          error={
+            name && !isValidISOAlias(name) ? (
+              <div className="alias-error">
+                Please enter only alphanumeric characters, periods (.) and
+                hyphens in this field
```
[the remark this answers is not in the document]
Comment (edlerd) [reply src/pages/storage/UploadCustomIso.tsx:135]: Oh yes, please :)

[the remark this answers is not in the document]
Comment (mas-who) [reply src/pages/storage/UploadCustomIso.tsx]: Done :+1:

**Review by edlerd — DISMISSED** [review]
Thx for the adjustments!

**Comment by edlerd** [comment]
The other two modals (instance and volume snapshot creation) have the same problem, that the width changes if the error gets visible.

**Comment by mas-who** [comment]
> The other two modals (instance and volume snapshot creation) have the same problem, that the width changes if the error gets visible.

Those should be fixed now.

**Review by edlerd — APPROVED** [review]
All good now, thanks for making this great :)
