### PR TITLE
fix(form) spacing for overflowing checkbox highlight.

### LINKED ISSUE #1862: Create / EditStorage Pool page checkbox is too close to the edge
Image

The checkbox in the Create / Edit Storage Pool page is too close to the edge which cuts off the focus effect.

### PR DESCRIPTION
**Pull request by edlerd**
## Done

-  fix spacing for overflowing checkbox highlight.
-  fix spacing for footer in volume creation in modal during instance edit/create.

Fixes #1862

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @Kxiru or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](https://github.com/canonical/lxd-ui/blob/main/CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - Create/edit an instance/profile/network/storage pool/storage volume and ensure the spacing in the configuration form is correct
    - Start a storage pool creation in a clustered environment. Ensure the outline of the "cluster member specific" input checkbox is not cut off on the left side
    - Start to edit/create and instance/profile and go to "devices" > "disk" > "attach a disk device" > "custom volume". Ensure the "create a volume" button has correct bottom padding.

## Screenshots

Before:

image

After:

image

Before:

image

After:

image

### CODE REVIEW

File: src/components/forms/ClusterSpecificInput.tsx [hunk 1]
```diff
@@ -69,7 +69,7 @@ const ClusterSpecificInput: FC<Props> = ({
 
   return (
     <div className={classname}>
-      {canToggleSpecific && !isReadOnly && (
+      {canToggleSpecific && !isReadOnly && memberNames.length > 1 && (
```
Comment (omarelkashef) [inline src/components/forms/ClusterSpecificInput.tsx]: This is breaking some network tests that are looking for this label.

File: src/pages/profiles/ProfileSelector.tsx [hunk 2]
```diff
@@ -180,18 +180,20 @@ const ProfileSelector: FC<Props> = ({
...
-          className="profile-add-btn"
-          onClick={addProfile}
-          type="button"
-          title={disabledReason}
-          hasIcon
-        >
-          <Icon name="plus" />
-          <span>Add profile</span>
-        </Button>
+        <div>
```
Comment (omarelkashef) [inline src/pages/profiles/ProfileSelector.tsx:183]: What does wrapping the button in a div do here?

File: src/pages/storage/forms/StorageVolumeFormMain.tsx [hunk 3]
```diff
@@ -168,31 +168,33 @@ const StorageVolumeFormMain: FC<Props> = ({
...
-              formik,
-              label: "Security shifted",
-              name: "security_shifted",
-              defaultValue: "",
-              disabled: formik.values.security_unmapped === "true",
-              disabledReason:
-                "This setting can't be changed while security unmapped is set to true",
-              children: <Select options={optionTrueFalse} />,
-            }),
+        <div>
```
Comment (omarelkashef) [inline src/pages/storage/forms/StorageVolumeFormMain.tsx:171]: What does the div do here as well?

File: src/components/forms/ClusterSpecificInput.tsx (hunk 1 above)
Comment (edlerd) [reply src/components/forms/ClusterSpecificInput.tsx]: I undid this and [filed a task](https://warthogs.atlassian.net/browse/WD-35391) to look into the tests together with bringing this change back.

File: src/pages/profiles/ProfileSelector.tsx (hunk 2 above)
Comment (edlerd) [reply src/pages/profiles/ProfileSelector.tsx:183]: Without the wrapper, the button gets stretched due to the left margin applied to it. The wrapper catches the margin, and the button starts nicely aligned with it.

image

File: src/pages/storage/forms/StorageVolumeFormMain.tsx (hunk 3 above)
Comment (edlerd) [reply src/pages/storage/forms/StorageVolumeFormMain.tsx:171]: Same as above, button would grow to the left without this.
