### PR TITLE
fix architecture filtering on image selection

### LINKED ISSUE #753: Error report
```
TypeError: va[m] is not iterable (cannot read property undefined)
    at https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/CreateInstance-17c2d93e.js:1:2734
    at Array.map (<anonymous>)
    at _a (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/CreateInstance-17c2d93e.js:1:2678)
    at ja (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/CreateInstance-17c2d93e.js:1:3934)
    at Zg (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:38:19529)
    at B1 (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:40:44027)
    at L1 (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:40:39763)
    at m$ (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:40:39691)
    at Cd (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:40:39545)
    at Ym (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:40:35913)
```

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- fix architecture filtering on image selection, it needs to deal with non-aliased architectures
- adding test for architecture alias loading

Fixes #753 

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @mas-who or @edlerd for access.
    - With a local copy of this branch, run as described [here](../HACKING.md#setting-up-for-development).
2. Perform the following QA steps:
    - browse images on instance create. Ensure the same architecture filters on the left are available as before.

### CODE REVIEW

File: src/util/architectures.tsx [hunk 1]
```diff
@@ -40,13 +40,16 @@ const ARCHITECTURE_ALIASES: Record<string, string[]> = {
...
+  const aliasKeys = Object.keys(ARCHITECTURE_ALIASES);
+
   names.map((value) => {
-    const key = Object.keys(ARCHITECTURE_NAMES).find(
-      (key) => ARCHITECTURE_NAMES[key] === value,
-    );
-    if (key) {
-      aliases.push(...ARCHITECTURE_ALIASES[key]);
+    const nameKey = nameKeys.find((key) => ARCHITECTURE_NAMES[key] === value);
+    const hasAlias = aliasKeys.some((aliasKey) => aliasKey === nameKey);
```
Comment (mas-who) [inline src/util/architectures.tsx:48]: maybe we can just check `if (nameKey in ARCHITECTURE_ALIASES)`?

**Review by mas-who — APPROVED** [review]

**Comment by mas-who** [comment]
LGTM :+1:
