### PR TITLE
fix(certificates) adjust onboarding steps for tls cert in chrome and chromium on linux

### LINKED ISSUE #1337: Certificate creation and installation instructions dont work for Chromium on Linux
When using Chromium on Linux (Version 137.0.7151.103 (Official Build) snap (64-bit)) the Chrome on Linux TLS instructions don't work because the import certificate stage fails

Image

Image

It seems that Chromium on Linux does not accept pfx files (I had to change the default file filter to all files to get it to show the downloaded file).

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- fix(certificates) adjust onboarding steps for tls cert in chrome and chromium on linux

Fixes #1337

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @Kxiru or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](https://github.com/canonical/lxd-ui/blob/main/CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - check the onboarding steps for chrome on linux

## Screenshots

image

### CODE REVIEW

File: src/pages/login/BrowserImport.tsx [hunk 1]
```diff
@@ -85,17 +85,21 @@ const BrowserImport: FC = () => {
...
-                Click <b>Import</b>
+                Click <b>Your certificates</b>
               </li>
               <li className="p-list__item">
-                Select the file you just downloaded (ending in .pfx). If you
-                created a password for the certificate, type it in now.
+                Go to <b>View imported certificates from Linux</b>
+              </li>
+              <li className="p-list__item">
+                Select <b>Import</b> and choose the file you just downloaded
```
Comment (Kxiru) [inline src/pages/login/BrowserImport.tsx]: Perhaps reword to "choose the .pfx file" to get rid of the info in parentheses?

**Review by Kxiru — COMMENTED** [review]
Minor copy suggestion but thanks for the logical rework!

File: src/pages/login/BrowserImport.tsx (hunk 1 above)
Comment (edlerd) [reply src/pages/login/BrowserImport.tsx]: Good idea. Adjusted the wording to be easier to read without the parentheses..

**Review by Kxiru — APPROVED** [review]
Looks good, thanks David!
