### PR TITLE
fix(pool) ceph source to be sent as cluster member specific config

### LINKED ISSUE #1526: Source and ceph.osd.data_pool_name ignored creating Ceph pool
Image

I already have a pool on my Ceph cluster named `lxd` and wish to use that.

The above configuration creates a new pool on my ceph cluster named `ceph`. The `Source` option is ignored.

https://documentation.ubuntu.com/lxd/latest/howto/storage_pools/

Other examples mention you have to specify `ceph.osd.pool_name=my-osd` (`lxc storage create pool3 ceph ceph.osd.pool_name=my-osd`) so I modified the YAML in the UI during creation like so:
```
name: ceph
description: ''
driver: ceph
config:
  source: lxd
  ceph.osd.data_pool_name: lxd
```
but LXD still decides to create a new pool on my Ceph cluster named `ceph`.

eventually I ended up creating it via the CLI like so:
```
root@emerald:/home/vos# lxc storage create ceph ceph source=lxd
Error: Config key "source" is cluster member specific
root@emerald:/home/vos# lxc storage create ceph ceph source=lxd --target sapphire
Storage pool ceph pending on member sapphire
root@emerald:/home/vos# lxc storage create ceph ceph source=lxd --target emerald
Storage pool ceph pending on member emerald
root@emerald:/home/vos# lxc storage create ceph ceph source=lxd --target ruby
Storage pool ceph pending on member ruby
root@emerald:/home/vos# lxc storage create ceph ceph source=lxd --target diamond
Storage pool ceph pending on member diamond
root@emerald:/home/vos# lxc storage create ceph ceph ceph.osd.data_pool_name=lxd
Storage pool ceph created
```

My LXD cluster now has a storage pool named `ceph` that points to the `lxd` pool on my Ceph cluster.

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- fix(pool) ceph source to be sent as cluster member specific config

Fixes #1526

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @Kxiru or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](https://github.com/canonical/lxd-ui/blob/main/CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - In a cluster with ceph configured
    - create a storage pool, specify a source
    - ensure the pool is created and on edit the source is displayed correctly on the pool configuration

### CODE REVIEW

File: src/pages/storage/forms/StoragePoolFormMain.tsx [hunk 1]
```diff
@@ -207,7 +206,14 @@ const StoragePoolFormMain: FC<Props> = ({ formik }) => {
               />
             ))}
           {hasSource &&
-            (hasClusterWideSource || !isClusteredServer(settings) ? (
+            (isClusteredServer(settings) ? (
+              <ClusteredSourceSelector
+                formik={formik}
+                helpText={sourceHelpText}
+                disabledReason={formik.values.editRestriction}
+                canToggleMemberSpecific={!isClusterWideSource}
```
Comment (Kxiru) [inline src/pages/storage/forms/StoragePoolFormMain.tsx:214]: The PR title implies we do want Ceph pools to be cluster member specific, but this addition prevents that. Is this intentional?

Comment (edlerd) [reply src/pages/storage/forms/StoragePoolFormMain.tsx:214]: Yes, the source config is the same for each member, the difference is that it needs to be included in the config sent to each member.
