### PR TITLE
Select 1st pool when configuring root storage

### LINKED ISSUE #342: Require selecting a storage pool, or leave the selected one
I used the UI to create an instance and wanted to increase the storage pool size, so I configured that before launching the instance:
Screenshot from 2023-05-12 14-00-13

The result was:
`Failed creating instance record: Failed initialising instance: Invalid devices: Device validation failed for \"root\": Root disk entry must have a \"pool\" property set`

Before I selected "Root storage pool" to configure the size, the `default` pool was selected there, so I didn't even look at the dropdown (the only thing I wanted to change was the size).
But as soon as I selected "Root storage pool", the dropdown selection changed to "Select option", and it let me launch the instance without selecting anything, which caused the error.

It makes sense in hindsight, but I think we could improve the usability here - either by requiring a pool to be selected, or by keeping the dropdown on `default` unless something else is selected.

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- automatically select the 1st pool, when overriding root storage, disallow to unselect the pool completely

Fixes #342 

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @lorumic or @edlerd for access.
    - With a local copy of this branch, run as described in the [Readme](https://github.com/canonical/lxd-ui#setting-up-for-development).
2. Perform the following QA steps:
    - Configure root storage on an instance/profil edit/creation

### CODE REVIEW

**Comment by al-bakalova** [comment]
@edlerd I am not sure what problem we are trying to solve here. Could we please review this one together tomorrow?

File: src/pages/instances/forms/RootStorageForm.tsx [hunk 1]
```diff
@@ -83,6 +84,7 @@ const RootStorageForm: FC<Props> = ({ formik, project }) => {
       return {
         label: storagePool.name,
         value: storagePool.name,
+        disabled: false,
```
Comment (lorumic) [inline src/pages/instances/forms/RootStorageForm.tsx:87]: Isn't this false by default? Do we need to specify it?

Comment (edlerd) [reply src/pages/instances/forms/RootStorageForm.tsx:87]: It's a way to keep the types similar without specifying the type of the objects in the options array.
