### PR TITLE
Take project resource limits into account for available limits

### LINKED ISSUE #1081: Bug: limits shown incorrect in a resource restricted project
Not a high priority bug or anything, just an oddity that I noticed !

Playing around with a restricted project, I set a limit on my project for max 5GB memory and 4 CPU cores.

**The "Create Instance" flow still shows the total cpu cores and max host memory as limits:**

Image

**Instance creation obviously fails:**

Image

Image

**The proper limits are also missing when editting an existing instance:**

Image

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- Take project resource limits into account for available cpu and memory limits.

Fixes #1081

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @mas-who or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](../CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - set up a project with cpu and / or memory limit. (Project configuration > Resource Limits > "Max sum of CPU" and "Max sum of memory limits"
    - configure a profile or instance, ensure the total available is in sync with system and project limitation
    - play with the project and instance/project limits to hit all different cases: project limit applies, resource limit applies, no project limit.

### CODE REVIEW

**Comment by mas-who** [comment]
## QA comments
1. Is it not worthwhile to show the host max CPU and memory for the corresponding project configs? I think it's possible right since we are showing those in the instance and profile pages.
2. Not sure if we should do anything about it, but this is an interesting behaviour. When setting the max cpu and memory configs for the project, if I have instances in the project with no limits applied (either directly or via profiles), I get the following error. This essentially blocks me from setting project limits before unless if I have limits set for all instances in the project.
Screenshot from 2025-01-31 09-47-22
3. Got the following error when I tried to set max CPU to 4, and error went away when I have set the limits to 12 as suggested by the error message. I'm not sure about the logic behind this though.
Screenshot from 2025-01-31 09-53-48

File: src/components/forms/CpuLimitSelector.tsx [hunk 1]
```diff
@@ -34,7 +36,17 @@ const CpuLimitSelector: FC<Props> = ({ cpuLimit, setCpuLimit }) => {
     notify.failure("Loading resources failed", error);
   }
 
-  const numberOfCores = resources?.cpu.total;
+  const getNumberOfCores = () => {
```
Comment (mas-who) [inline src/components/forms/CpuLimitSelector.tsx:39]: maybe we can have this as a utils function that take `project` and `resources` as inputs? We can then reuse this in the project settings page to display system limits

File: src/components/forms/MemoryLimitSelector.tsx [hunk 2]
```diff
@@ -40,7 +43,19 @@ const MemoryLimitSelector: FC<Props> = ({ memoryLimit, setMemoryLimit }) => {
     notify.failure("Loading resources failed", error);
   }
 
-  const maxMemory = resources?.memory.total;
+  const getAvailableBytes = (): number => {
```
Comment (mas-who) [inline src/components/forms/MemoryLimitSelector.tsx:46]: same comment here, we could have this as a utils function? This will probably need to combine with `getAvailableMemory` below though

**Review by mas-who — COMMENTED** [review]
Thanks for this, left some QA and code comments. Once the project limits are set (noting that it's blocked if any instances in the project have no limits), profile and instance creation works nicely with respect to resource limits.

File: src/components/forms/CpuLimitSelector.tsx (hunk 1 above)
Comment (edlerd) [reply src/components/forms/CpuLimitSelector.tsx:39]: That is a good idea, because on configuring the project you will want to know the system details.

**Comment by edlerd** [comment]
@mas-who I accidentally pushed to the wrong branch this morning and requested a review. Pushed the right changes just now.

**Comment by mas-who** [comment]
@edlerd code and QA all looks good :+1: I think the errors that I pointed out in my previous QA comments are inherent to lxd's behaviour, so it's not an UI issue. The e2e tests are failing probably because the new `CpuLimitInput` component.

**Comment by edlerd** [comment]
Fixed the type of the cpu input to always contain text and number correctly. @mas-who can you have another look at this one?

**Review by mas-who — APPROVED** [review]
LGTM :+1:
